const dupa = {
    'Vegetable Trimmings ': 12,
    'Food Scraps ': 15,
    'Coffee Grounds ': 20,
    'Spent Brewery Grains ': 18,
    'Chicken Manure ': 6,
    'Pig Manure ': 13,
    'Sheep/Goat/Rabbit Manure ': 14,
    'Dairy Cow Manure ': 30,
    'Cattle Manure ': 18,
    'Llama Manure ': 20,
    'Horse Manure ': 22,
    'Spent Mushroom Substrate ': 16,
    'Tree Trimmings - Fresh ': 16,
    'Grass Clippings ': 19,
    'Weeds ': 20,
    'Alfalfa Hay ': 18,
    'Hay - General ': 25,
    // BROWNS
    'Garden Trimmings ': 30,
    'Leaves - Fresh ': 37,
    'Shrub Trimmings ': 53,
    'Leaves - Dry Loose ': 54,
    'Coco Coir ': 90,
    'Peat Moss ': 60,
    'Leaves - Moist, Compacted ': 54,
    'Corn Stalks ': 60,
    'Pine Needles ': 80,
    'Bark - Hardwoods ': 223,
    'Bark - Softwoods ': 496,
    'Office Paper ': 129,
    'Paper Towel/Napkiin - Soiled ': 150,
    'Newsprint ': 170,
    'Paper Towels/Napkins - Clean ': 275,
    'Cardboard ': 563,
    'Straw - Oat ': 60,
    'Straw - General ': 80,
    'Straw - Rye ': 82,
    'Straw - Wheat ': 127,
    'Chips - Hardwoods ': 560,
    'Chips - Softwoods': 641,
    'Sawdust ': 625,
}
